#include "..header/gameBoard.h"
#include "..header/pacman.h"
#include "stdio.h"
#include "stdlib.h"

void gameBoardInitialize(GameBoard *a)
{
    char wall= '3';
    char fruit1 = '-';
    char fruit2 = 'O';
    char fruit3 = '&';
    char fruit4 = '@';
    char map[20][26];  //map generated by text file
    int numFruit1=0; //number of first fruit on level
    int numFruit2=0; //number of second
    int numFruit3=0; //number of thrid
    int numFruit4=0; //number of fourth
    int pacman=1;    //number of pacman
    int monster=0;    //number of monsters
    int pause_state=0;
    int run_state=0;
  	int test=0;
}

void gameBoardLoad()
{   FILE* fp = NULL;
    char c;
    int i,j;

    struct GameBoard gameboard;
    struct PacMan pacman;
    fp = fopen("stage1.txt", "r");

    if (!fp)
        exit(1);

    for ( i = 0; i < 20; i++ )
    { for (j=0; j<27; j++)
  	{
        c = getc(fp);
	    gameboard.map[i][j]=c;
		if(c=='-')
		     gameboard.numFruit1++; //count how many fruit1

    if(c=='O')
         gameboard.numFruit2++; //count how many fruit2

    if(c=='&')
          gameboard.numFruit3++; //count how many fruit3

    if(c=='@')
          gameboard.numFruit3++; //count how many fruit4

		if(c=='<')
		{ pacman.x_start=i;    //set initial position of PacMan
		  pacman.y_start=j;}

    if(c=='M')
        gameboard.monster++; //count how many monster
    }}

     fclose(fp);
}
