//#include "..header/gameBoard.h"
//#include "..header/pacman.h"
#include "stdio.h"
#include "stdlib.h"

typedef struct GameBoard
{
    char wall;
    char fruit1, fruit2, fruit3, fruit4;
    char map[20][26];  //map generated by text file
    int numFruit1; //number of first fruit on level
    int numFruit2; //number of second
    int numFruit3; //number of thrid
    int numFruit4; //number of fourth
    int pacman;    //number of pacman
    char sprite;
} GameBoard;

typedef struct PacMan
{
    int x_start;
    int y_start;
    char sprite;
} PacMan;

typedef struct Monster
{
    int start_positionX;
    int start_positionY;
    char sprite;
} Monster;

char fruit[20][26];

void pacmanInitialize(PacMan*);
void gameBoardInitialize(GameBoard *a);
void displayBoard(struct GameBoard gameboard);
void monsterInitialize(Monster*);

void gameBoardInitialize(GameBoard *a)
{
    char wall= '3';
    char fruit1 = '-';
    char fruit2 = '*';
    char fruit3 = '&';
    char fruit4 = '@';
    int numFruit1=0; //number of first fruit on level
    int numFruit2=0; //number of second
    int numFruit3=0; //number of thrid
    int numFruit4=0; //number of fourth
    int pacman=1;    //number of pacman
}

void pacmanInitialize(PacMan *a)
{
    a->y_start = 0;
    a->x_start = 0;
    a->sprite = '<';
}

void monsterInitialize(Monster *a)
{
    a->start_positionX=0;
    a->start_positionY=0;
    a->sprite='M';

}

void displayBoard(struct GameBoard gameboard)
{
    int i,j;

    for ( i = 0; i <20; i++ ){
        for (j=0; j<26; j++)
	{
	    int a=0;
	    if(gameboard.map[i][j]>0)

        { printf("%c", gameboard.map[i][j]);
          a=1; }

        if(fruit[i][j]>0)
        printf("%c", fruit[i][j]);

        if(fruit[i][j]=='\0' && a==0)
        printf(" ");

    }
    }
}


int main ()
{
    FILE* fp = NULL;
    char c;
    int i,j;

    struct GameBoard gameboard;
    struct PacMan pacman;
    struct Monster monster;

    fp = fopen("stage1.txt", "r");
    if (!fp)
        exit(1);

    gameBoardInitialize(&gameboard);
    pacmanInitialize(&pacman);
    monsterInitialize(&monster);

    gameboard.numFruit1=0;
    gameboard.numFruit2=0;
    gameboard.numFruit3=0;
    gameboard.numFruit4=0;

    for ( i = 0; i < 20; i++ )
    { for (j=0; j<26; j++)
	{
        c = getc(fp);
        if(c=='3' || c=='\n' || c==' ' || c=='M')
            gameboard.map[i][j]=c;
        else
            gameboard.map[i][j]=0;

       if(c=='-' || c=='*' || c=='&' || c=='$')
        fruit[i][j]=c;

    if(c=='-')
        gameboard.numFruit1++;

         if(c=='*')
            gameboard.numFruit2++;

            if(c=='&')
      		     gameboard.numFruit3++;

               if(c=='$')
                  gameboard.numFruit4++;

        if(c=='<')
	   	{ gameboard.map[i][j]=c;
          pacman.x_start=i;
          pacman.y_start=j;}

        if(c=='M')
        { gameboard.map[i][j]=c;
          monster.start_positionX=i;
          monster.start_positionY=j;}

    }
    }

    fruit[0][0]=0;
    fruit[0][1]=0;
    displayBoard(gameboard);
    printf("\nNum of Fruit1: %d", gameboard.numFruit1);
    printf("\nNum of Fruit2: %d", gameboard.numFruit2);
    printf("\nNum of Fruit3: %d", gameboard.numFruit3);
    printf("\nNum of Fruit4: %d", gameboard.numFruit4);
    printf("\nPacMan x,y pos: %d,%d", pacman.x_start, pacman.y_start);
    printf("\nMonster x,y pos: %d,%d", monster.start_positionX, monster.start_positionY);
    fclose(fp);
    return 0;
}
