#ifndef _DATA_H
#define _DATA_H

typedef struct PacMan
{
  int lives;
  int x_position;
  int y_position;
  int x_direction;
  int y_direction;
  int score;
  char sprite;
} PacMan;

typedef struct Monster
{
  int start_positionX;
  int start_positionY;
  int x_position;
  int y_position;
  int x_direction;
  int y_direction;
  char sprite;
} Monster;

typedef struct Fruit
{
  int point_value;
  int x_position;
  int y_position;
  char sprite;
} Fruit;

typedef struct Direction
{
  int x;
  int y;
} Direction;

typedef struct GameBoard
{
  char map[][];  //map generated by text file
  int numFruit1; //number of first fruit on level
  int numFruit2; //number of second
  int numFruit3; //number of thrid
  int numFruit4; //number of fourth
  int pacman;    //number of pacman
  int monster    //number of monsters
} GameBoard;

#endif
