#ifndef GAMEBOARD_H
#define GAMEBOARD_H
#include "../header/gameboard.h"
#include "../header/pacman.h"
#include "../header/monster.h"
#include "../header/fruit.h"
#include "stdio.h"
#include <stdlib.h>
#include <ncurses.h>

typedef struct Direction
{
    int x;
    int y;
} Direction;

typedef struct GameBoard
{
    char wall;
    char fruit1, fruit2, fruit3, fruit4;
    char map[20][26];  //map generated by text file
    int numFruit1; //number of first fruit on level
    int numFruit2; //number of second
    int numFruit3; //number of thrid
    int numFruit4; //number of fourth
    int numPacman;    //number of pacman
    int numMonster;    //number of monsters
    int pause_state;
    int run_state;
} GameBoard;

void draw_borders(WINDOW *);
void gameBoardInitialize(GameBoard *);
void displayBoard(GameBoard *, WINDOW *);
int gameBoardLoad(GameBoard *, PacMan *, Fruit [][26], char []);

#endif
