#ifndef GAMEBOARD_H
#define GAMEBOARD_H
#include "pacman.h"
#include "monster.h"
#include "fruit.h"
#include <stdio.h>
#include <stdlib.h>
#include <ncurses.h>

typedef struct Direction
{
    int x;
    int y;
} Direction;

typedef struct GameBoards
{
    char wall;          //char to hold wall
    char fruit[4];      //char array to hold fruit
    char map[20][26];   //map generated by text file
    int numFruit1;      //number of first fruit on level
    int numFruit2;      //number of second
    int numFruit3;      //number of thrid
    int numFruit4;      //number of fourth
    int numPacman;      //number of pacman
    int numMonster;     //number of monsters
    int pause_state;    //for pause loop
    int run_state;      //for run loop
} GameBoard;

void draw_borders(WINDOW *);
void gameBoardInitialize(GameBoard *);
void displayBoard(GameBoard *, WINDOW *);
int gameBoardLoad(GameBoard *, PacMan *, Fruit [][26], char []);
int numBytesRead(FILE *);

#endif
